name: 'Setup Container Environment'
description: 'Common setup steps for container-based jobs'
inputs:
  init-submodules:
    description: 'Initialize git submodules'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Configure git safe directory
      shell: sh
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Setup Rust environment
      shell: sh
      run: |
        . /root/.cargo/env
        rustup default stable 2>/dev/null || true

    - name: Initialize submodules
      if: inputs.init-submodules == 'true'
      shell: sh
      run: git submodule update --init --recursive

    - name: Install PDM dependencies
      shell: sh
      working-directory: gateware
      run: pdm install
