M48
; DRILL file {KiCad 9.0.2} date 2025-06-25T16:41:34+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-06-25T16:41:34+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0630
%
G90
G05
T1
X1.1669Y-2.6549
T2
X0.3795Y-2.6549
M30
